### ISSUE TITLE
Support newer pipenv versions

### ISSUE THREAD

**Issue by agelter** [michael-christen/dh-pipenv#2]
Thanks for creating this shim, just what I needed!  Any plans for supporting newer versions of pipenv?  It appears that something changed in newer versions and I am unable to create a working debian package with anything after pipenv==9.0.1.  As of today, pipenv is up to v2018.5.18 (which came after v11.10.4).  Thanks!

**Comment by agelter** [comment]
I should correct myself.  Looks like pipenv up to 11.0.x works with dh-pipenv.  Once I get to 11.1.x I start getting errors.

**Comment by michael-christen** [comment]
Hi Aaron, thanks for the interest in this, glad to hear it was helpful.

Unfortunately, I'm no longer actively supporting this, but just generating a `requirements.txt` with the `pipenv lock -r` command and using `dh-virtualenv` the standard way. I was using this tool to understand the internal mechanisms behind `dh-virtualenv` and ended up discovering that it'd be easier to simply generate the `requirements` file.

If you'd like to continue development of the repo feel free to fork it, or I could make you a contributor if you'd like.

Thanks again, let me know if there's anything else I can do.

**Comment by agelter** [comment]
Okay, that makes sense, actually!  Can I ask how you call `pipenv lock -r` from within your `debian/rules` file?  Do you call it explicitly before the `dh $@ --with python-virtualenv` call? If so, what if pipenv isn't installed?  Or do you call it as part of the actual `dh_virtualenv` call somehow?

**Comment by agelter** [comment]
Ah, my guess is that you probably make `pipenv` a build dependency in `debian/control` and then you can just call `pipenv lock -r` before you run `dh_virtualenv`.  Is that how you're doing it now?

**Comment by michael-christen** [comment]
I have a makefile that looks something like this:

```
requirements.txt:
    pipenv lock -r > requirements.txt

.PHONY: build_package
build_package: requirements.txt
    dpkg-buildpackage -us -uc
```

It's just a requirement of the system that `pipenv` is already setup (so specifying it as a build dependency works), for our production setup I've added other checks and conditions, but this should get you going.
